{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 2}, "tests": {"0": {"status": "ERROR", "message": "cls = <class 'drive_automation_test.TestMiscellaneousActions'>\n\n    @classmethod\n    def setup_class(cls):\n>       super(cls, TestMiscellaneousActions).setup_class()#FIRST SUPER CLASS\n\ndrive_automation_test.py:109: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ncls = <class 'drive_automation_test.TestMiscellaneousActions'>\n\n    @classmethod\n    def setup_class(cls):\n        cls.driver = Chrome(service=ChromeService(executable_path=\"./chromedriver.exe\"))\n        cls.web_driver_wait = WebDriverWait(cls.driver, 10)\n        cls.helper =  Helper(cls.driver, cls.web_driver_wait)\n>       cls.button_clicker = ButtonClicker(cls.driver, cls.web_driver_wait, cls.helper)\nE       TypeError: ButtonClicker.__init__() takes 3 positional arguments but 4 were given\n\ndrive_automation_test.py:49: TypeError\n", "test_name": "test_share_via_link", "rerun": "0"}, "1": {"status": "ERROR", "message": "cls = <class 'drive_automation_test.TestMiscellaneousActions'>\n\n    @classmethod\n    def setup_class(cls):\n>       super(cls, TestMiscellaneousActions).setup_class()#FIRST SUPER CLASS\n\ndrive_automation_test.py:109: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ncls = <class 'drive_automation_test.TestMiscellaneousActions'>\n\n    @classmethod\n    def setup_class(cls):\n        cls.driver = Chrome(service=ChromeService(executable_path=\"./chromedriver.exe\"))\n        cls.web_driver_wait = WebDriverWait(cls.driver, 10)\n        cls.helper =  Helper(cls.driver, cls.web_driver_wait)\n>       cls.button_clicker = ButtonClicker(cls.driver, cls.web_driver_wait, cls.helper)\nE       TypeError: ButtonClicker.__init__() takes 3 positional arguments but 4 were given\n\ndrive_automation_test.py:49: TypeError\n", "test_name": "test_view_file_info", "rerun": "0"}}, "suite_name": "drive_automation_test.py"}}}, "date": "March 18, 2024", "start_time": 1710770341.1338809, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "0", "skip": "0", "error": "2", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "2"}