{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 2}, "tests": {"0": {"status": "ERROR", "message": "@pytest.fixture(autouse=True, scope=\"session\")\n    def driver():\n>       instance = Chrome(executable_path=\"./chromedriver.exe\")\nE       TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'\n\ndrive_automation_test.py:22: TypeError\n", "test_name": "test_share_via_link", "rerun": "0"}, "1": {"status": "ERROR", "message": "@pytest.fixture(autouse=True, scope=\"session\")\n    def driver():\n>       instance = Chrome(executable_path=\"./chromedriver.exe\")\nE       TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'\n\ndrive_automation_test.py:22: TypeError\n", "test_name": "test_view_file_info", "rerun": "0"}}, "suite_name": "drive_automation_test.py"}}}, "date": "March 18, 2024", "start_time": 1710767372.5273833, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "0", "skip": "0", "error": "2", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "2"}